### ISSUE TITLE
Update the home page with current information

### ISSUE THREAD

**Issue by spencerarrasmith** [RocketLeagueMapmaking/RL-docs#16]
**Is your feature request related to a problem? Please describe.**
The home page should talk about the most recent mapmaking contest, and also have a section on RLBot Story Mode ++

**Describe the solution you'd like**
Write stuff

**Describe alternatives you've considered**
There are no alternatives

**Additional context**
Get it done

**Comment by webbuildlucas** [comment]
My thoughts for the home page:
- a hero section with primary button `Get started with UDK` and a second button `Explore documentation`
- a section which showcases the n newest maps
- a section about the map contests (linking to a page with a overview of all map contests) and RLBot Story Mode ++ (/current big project)
- a section with some workshop statistics with a button `Browse all maps` and some highlighted pages / links such as: 
     - for the latest things: framework updates (discord channel) and roadmap (link to trello board or roadmap page)
     - for getting help: RLMM discord server and FAQ (+ search button?)

Some general thoughts on the website:
- we could use [angolia search](https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-search) as it seems to give better matches or make our custom search option (angolia search seems to be already integrated for a part)
- we could improve the seo of website and fill the [frontmatter](https://vuepress.vuejs.org/guide/frontmatter.html#frontmatter) of a page more to get more consistency and add a default example in [the contributing guide](https://rocketleaguemapmaking.com/more/contribute.html) (and improve the wording on the page)

**Comment by spencerarrasmith** [comment]
Updated with `udk` PR merge
