### ISSUE TITLE
[FEATURE] Image path using alias instead of relative path

### ISSUE THREAD

**Issue by webbuildlucas** [RocketLeagueMapmaking/RL-docs#21]
**Is your feature request related to a problem? Please describe.**
To speed up the process of making pages we can use the vuepress feature [alias](https://vuepress.vuejs.org/guide/assets.html#relative-urls)

**Describe the solution you'd like**
in `config.js` add in `module.exports`:
```js
configureWebpack: {
    resolve: {
      alias: {
        '@images': '/docs/.vuepress/public/images/',
        '@icons': '../../.vuepress/public/icons/',
        '@kismet': '../../.vuepress/public/images/kismet/'
      }
    }
  }
```
I suggest to add `@kismet` for support of kismet images outside the kismet node component (#20 ) as the guide probably will use multiple kismet images.

In any link to an image we can then replace the relative url such as `../../.vuepress/public/images/image10.png` with `~@images/image10.png`

To make this work for all images there should be no images inside the `public` folder and possibly all images related to blender in `/images/blender/`, etc.

**Describe alternatives you've considered**
Using the 'old' method of relative paths, but as we have around 300+ links that needs to be replaced it might take a while

**Additional context**
none

**Comment by spencerarrasmith** [comment]
Merged branch `general-edits` into master
