### ISSUE TITLE
[FEATURE] Customization options

### ISSUE THREAD

**Issue by ghostrider-05** [RocketLeagueMapmaking/RL-docs#24]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but it is always nice to have more customization options. I assume most map makers uses UDK only to make RL maps, so changing UDK shouldn't be a problem.

**Describe the solution you'd like**
A miscellaneous page with (small) topics:
- setting world info (might also be in a UDK Advanced page like Map settings where more map config stuff is done)
- setting [custom splash screen in UDK](https://discord.com/channels/711882968200904715/711884447225610251/801542212399136838) and changing splash screen size (maybe add some custom messages when loading?)
 - replace the kismet background? It probably uses an image that can be replaced
 - adding your own buttons to UDK
 - toggle dark mode?

The setup script would then have a default RLMM splash screen (and custom RLMM kismet background). Beside this it also could have:
- custom UDK tips relevant to map making. The list of UDK tips can be found in 
`{UDK Folder}/Engine/Localization/INT/EditorTips.int`
- changes in the UDK tool bar:
    - add `CookedPCconsole` folder under File -> open
    - add `Templates` with a list of (own) map templates above File -> Import (or replace existing templates)
    - replace welcome message with useful links (who would want to go to the facebook page of UDK?)
    - add `Replace in RL` which would replace the map with `Labs_Utopia_P` in the Build options or in general a button in UDK that would replace the map (and open rocket league if not already open)
    - add `My maps` under File -> Recent which would display all your own maps in a folder (assuming you put all your maps there, make use of the folder setup made in the setup script)
    - add a button (/buttons) which would add common items (sorry mr swaggles, but the fastest way would be in the editor itself)
    - add links to the discord and website in the Help tool bar
  
**Describe alternatives you've considered**
None

**Additional context**
I havent looked into how to make custom button functionality, but it should be possible. It might be nice to include this in the setup script

**Comment by webbuildlucas** [comment]
## Replacing welcome menu
- messages: replace the messages mentioning `welcome screen` in 
`{UDK Folder}\Engine\EditorResources\WPF\Localized\UnrealEd.INT.xaml`
- images + background: replace the images in `<style>` with own images (can be located in any folder) in 
 `{UDK Folder}\Engine\EditorResources\WPF\Controls\WelcomeScreen.xaml`
- links: not discovered

**Comment by MrPh1l** [comment]
### Include template maps in UDK
This will be helpful for newcomers.
It's as simple as following [this tutorial](https://www.worldofleveldesign.com/categories/udk/udk-custom-map-template.php).

**Comment by webbuildlucas** [comment]
More suggestions:
- Allow player to choose which map will be opened automatically when UDK starts or have a template map 
- Change base import and export folder according to [the project setup](https://www.rocketleaguemapmaking.com/essential/05_project_setup.html), can be changed in `Engine\Config\BaseEditorUserSettings.ini`
- Change background color to another color for an empty scene (also in `BaseEditUserSettings.ini`)
- Change autosave options?

Other:
- update map template in the `Workshop` folder
